### ISSUE TITLE
Automatically update gridware packages

### ISSUE THREAD

**Issue by mjtko** [alces-software/clusterware#121]
In a similar fashion to yum we should cause gridware actions to automatically update repos after a configurable period of time.

**Comment by bobwhitelock** [comment]
Let me see if I understand what is required for this:
1. There's a config value for the amount of time before automatically updating repos (probably in `$cw_ROOT/etc/gridware.rc` and set as a number of days).
2. Before running a gridware command we check if this time has passed and an update has not happened yet.
3. If we need to run an update, we prompt the user to confirm if they want to do this first or carry on running their command (or do we just always do the update without asking them?).
4. If yes, the update is run, and this is similar to running `alces gridware update $repo` for each enabled repo.

Is this what you were thinking of?

Also regarding (2), do we want to reset the time until next update after a manual update, or should it always reoccur after a constant period?

Regarding (3), if we do prompt the user and they don't want to update, how long should we wait before next asking them?

**Comment by bobwhitelock** [comment]
Having investigated further it seems `$cw_GRIDWARE_root/etc/gridware.yml` is the more sensible home for the config value mentioned in (1).

**Comment by mjtko** [comment]
Yup, this is what I was thinking of!

To address some of the points:

(2) I think reset the time after a manual update.
(3) I think we should always do the update without asking.

**Comment by bobwhitelock** [comment]
Hey @mjtko - a few more questions from things I've run into:
1. Currently there can be multiple repos, and you can update any one of these at a time - any thoughts on how this should work with automatically updating all the repos when its been some amount of time since an update? As in:
   
   a. If we only track one time for last update, the automatic updates of all repos may never run if a user keeps one of their repos up-to-date while not updating the others.
   
   b. If we track a last update time for each repo, should we then check each of these in turn when a gridware command is run and only update the ones surpassing the update period?
2. Presumably certain commands shouldn't trigger automatic updates, such as `help` (might be confusing), `update` (already updating), `depot` commands (use different repos)?
3. Do we need similar automatic updates for depot repos?

**Comment by mjtko** [comment]
1. I think (b) is sensible.
2. Yes. Probably whitelist rather than blacklist. These ones seem sensible to update prior to execution: `import`, `info`, `install`, `list`, `requires`, `search`.
3. That makes sense. Probably triggered on: `info`, `install`, `list`

**Comment by bobwhitelock** [comment]
Thanks :+1:

**Comment by bobwhitelock** [comment]
I've realised I forgot to include doing this for depot actions also (as discussed) - can add this when I finish what I'm working on currently or add a card to get back to this later.

**Comment by mjtko** [comment]
Add an issue to get back to this later I think. This is pretty self-contained as is and I'm keen to get it completed and merged through.
