### ISSUE TITLE
Option to enable various HPC optimizations for Flight compute nodes

### ISSUE THREAD

**Issue by wdm78** [alces-software/clusterware#191]
In a similar vein to adding support for turning off hyperthreading, there are a few more common optimizations that would be useful to be able to trigger when running HPC clusters. This is an enhancement request with no immediate requirement, but it'd be nice to have support for these as they are very common HPC settings we use every time we run benchmarks. We run these commands manually (or as part of job-scripts) currently. 

Here is a list of enhancements we commonly perform (as root user):
- disable THP (useful on all EL7) - `echo never > /sys/kernel/mm/transparent_hugepage/enabled`
- switch clocksource to TSC (useful on hypervised environments only - e.g. AWS) - `echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource`
- prepare Linux for having no swap memory configured (useful anywhere that doesn't have swap memory) - `echo 0 > /proc/sys/vm/swappiness`
- clear vfscache out (useful on all EL, and prevents a number of commercial apps from complaining) - `echo 1 > /proc/sys/vm/drop_caches`

None of these optimisations should be made automatically, but it would be useful if a cluster-wide setting was obeyed by new nodes joining the cluster.

**Comment by mjtko** [comment]
- disable THP - this seems like a good candidate for an `alces configure` subcommand - `alces configure thp` or similar
- switch clocksource - does it sometimes make sense not to do this for hypervised environments? Otherwise it seems that it would be sensible to do this automatically it if we detect we're running in that kind of environment.
- no swap memory - again, if there's no swap detected, does it make sense to not set this automatically?
- clear vfscache - this seems more like an instruction than a configuration value if my understanding that this affects the system instantaneously but then the vfs cache can fill up again is correct. In that situation, this would seem to be more suited to some kind of command (not sure we have anywhere suitable to slot this in atm but, as an example, perhaps we could configure a `drop_cache` command that can be called from within job scripts or manually at the command line?

@wdm78: can you comment please?

**Comment by wdm78** [comment]
Thanks for the update - 

_disable THP - this seems like a good candidate for an alces configure subcommand - alces configure thp or similar_

Yep - agreed

_switch clocksource - does it sometimes make sense not to do this for hypervised environments? Otherwise it seems that it would be sensible to do this automatically it if we detect we're running in that kind of environment._

That seems reasonable; in theory, some clocksources seem to be "better" than others for certain types of hypervisor, but TSC isn't a bad one to choose. 

_no swap memory - again, if there's no swap detected, does it make sense to not set this automatically?_

Good point - yes; if there is no swap, we should set this. However, if swap gets configured manually, then this setting will mean the kernel won't automatically use it (which I think is fine). 

_clear vfscache - this seems more like an instruction than a configuration value if my understanding that this affects the system instantaneously but then the vfs cache can fill up again is correct. In that situation, this would seem to be more suited to some kind of command (not sure we have anywhere suitable to slot this in atm but, as an example, perhaps we could configure a drop_cache command that can be called from within job scripts or manually at the command line?_

Yes - that's true; this is something a user might want to call periodically, rather than "set" as a configuration variable. Really we just need a command that does this that the (non-root) user can call easily - running "sudo echo 1 > /proc/sys/vm/drop_caches" doesn't work for reasons that might not be immediately obvious to a user. 

Thanks!

**Comment by mjtko** [comment]
THP behaviour control added in https://github.com/alces-software/clusterware/commit/6f43217f4a811beb2bc5d2f3681d654263ef56f9

**Comment by WilliamMcCumstie** [comment]
As discussed with @mjtko.

For the time being, we can put the drop `vfscache` under `alces configure` until such time that a more suitable location is found. 

So the command would be:
`alces configure dropcache <pagecache|slabobjs|both>` where those values map to `1`, `2` or `3` respectively

**Comment by mjtko** [comment]
The `dropcache` command was added in https://github.com/alces-software/clusterware/commit/f63281e21b1d4c2732f8f3d64e790b8aab181ac7
