### ISSUE TITLE
Dealing with hosts leaving

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#58]
Currently when a host is destroyed, all traces of it remain in the environment (SGE, /etc/hosts, genders etc.). 

Is it possible for us to check, and perhaps set a time limit (say 5/10 minutes or so) - if the node isn't seen again in that time, remove all trace of it.

**Comment by sierra-tango-echo** [comment]
this is primarily for dynamic cluster creation / tear down (ie the nodes will never be seen again). We don't always want to get rid of nodes because sometimes they may well come back - but in this case we're never gonna see the nodes again - so over a few weeks running the qhost entry could be hundreds of 'off' nodes long. Maybe we could have something we enabled/disabled per image?

**Comment by mjtko** [comment]
This is something I'd been wanting to implement for a while!

The implementation is on by default, and removes nodes when they leave the cluster ring (via `member-leave` [graceful] or `member-failed` [ungraceful] events).

This behaviour can be turned off (say, for the semi-permanent cluster scenario) by setting `cw_CLUSTER_SGE_clean` to anything other than `true` in `/opt/clusterware/etc/cluster-sge.rc` which is created when the `cluster-sge` handler is enabled.

(This feature will be available in Clusterware >= 1.3.0.)
